"""Cypher DDL emitter — generates Neo4j constraints and indexes."""

from pathlib import Path

from linkml_runtime.utils.schemaview import SchemaView

LAYERS = ["core", "epidemiology", "formulary", "ethnobotany"]


def _layer_for_class(sv: SchemaView, class_name: str) -> str:
    """Map a class to its schema layer.

    Falls back to ``core`` when the layer cannot be inferred.
    """
    c = sv.get_class(class_name)
    # linkml-runtime classes expose `in_subset` as a list of subset names
    subsets = getattr(c, "in_subset", None) or []
    for subset in subsets:
        if subset in LAYERS:
            return subset  # type: ignore[no-any-return]
    return "core"


def emit_cypher(schema_path: Path, output_dir: Path) -> None:
    """Write Cypher DDL files, one per layer."""
    sv = SchemaView(str(schema_path))
    output_dir.mkdir(parents=True, exist_ok=True)

    # Group classes by layer
    layer_classes: dict[str, list[str]] = {layer: [] for layer in LAYERS}
    for class_name in sv.all_classes():
        layer = _layer_for_class(sv, class_name)
        layer_classes[layer].append(class_name)

    for layer in LAYERS:
        lines: list[str] = [
            f"// Cypher DDL for {layer} layer",
            "// Generated by scripts/emit.py — DO NOT EDIT BY HAND",
            "",
        ]
        for class_name in sorted(layer_classes[layer]):
            # Primary identifier constraint (class name + id)
            lines.append(f"CREATE CONSTRAINT {class_name}_id IF NOT EXISTS")
            lines.append(f"  FOR (n:{class_name})")
            lines.append("  REQUIRE n.id IS UNIQUE;")
            lines.append("")
            # Indexes on relationship slots
            for slot_name in sv.class_slots(class_name):
                slot = sv.induced_slot(slot_name, class_name)
                range_cls = getattr(slot, "range", None)
                if range_cls and range_cls in sv.all_classes():
                    lines.append(f"CREATE INDEX {class_name}_{slot_name}_idx IF NOT EXISTS")
                    lines.append(f"  FOR (n:{class_name})")
                    lines.append(f"  ON (n.{slot_name});")
                    lines.append("")
        (output_dir / f"{layer}.cypher").write_text("\n".join(lines))
